# Site settings
title: Cloud Surfer
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of code snippets and some thoughts from Sach Warah, a pilot, engineer and coder. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sachwarah.github.io" # the base hostname & protocol for your site
twitter_username: sachwarah
github_username: sachwarah
# Build settings
markdown: kramdown
# Excerpt stuff
excerpt_separator: <!--more-->
